export class JobseekersData {
    lastName : string;
    firstName : string;
    middleInitial: string;
    address: string;
    city: string;
    state: string;
    zip: string;
    homePhone: string;
    cellPhone: string;
    email: string;
    ssn: string;
    selectedOption: string;
    emergencyContact: string;
    emergencyPhone: string;
    positions: string;
    unavailable: string;
    highSchoolName: string;
    highSchoolAddress: string;
    highSchoolYears: number;
    highSchoolDegree: string;
    collegeName: string;
    collegeAddress: string;
    collegeYears: number;
    collegeDegree: string;
    tradeName: string;
    tradeAddress: string;
    tradeYears: number;
    tradeDegree: string;
    graduateName: string;
    graduateAddress: string;
    graduateYears: number;
    graduateDegree: string;
    refName1:string;
    refPosition1: string;
    refAddress1: string;
    refPhone1: string;
    refName2: string;
    refPosition2: string;
    refAddress2: string;
    refPhone2: string;
}